services:
  - type: web
    name: ai-news-aggregator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:///news.db   # Change to your PostgreSQL/MySQL URI in production
